'use client';

import { ThemeProvider } from "next-themes";
import { Cairo, Tajawal } from "next/font/google"; // استيراد الخطوط
import "./globals.css";
import Header from "@/components/Navbar";
import Footer from "@/components/Footer";
// import { SessionProvider } from "next-auth/react";
import Head from 'next/head';

// تحميل الخطوط
const cairo = Cairo({ subsets: ["latin"], weight: "700" }); // خط الإنجليزي
const tajawal = Tajawal({ subsets: ["arabic"], weight: "400" }); // خط العربي



export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className={cairo.className}>
       <Head>
        <title>Learn Languages - Human and Programming Languages</title>
        <meta name="description" content="Learn various languages including Arabic, English, Turkish, and programming languages like HTML, CSS, JavaScript, and more." />
        <meta name="keywords" content="Learn Languages, Arabic, English, Turkish, Language Learning, Linguistics, Programming Languages, HTML, CSS, JavaScript, Python" />
      </Head>
      <body>
        <ThemeProvider attribute="class" defaultTheme="dark"> 
           {/* <SessionProvider> */}
            <Header />
            <main className={tajawal.className}>
              {children}
            </main>
            {/* تطبيق خط Tajawal للنصوص العربية */}
            <Footer />
          {/* </SessionProvider>  */}
        </ThemeProvider>
      </body>
    </html>
  );
}





// import type { Metadata } from "next";
// import { Inter } from "next/font/google";
// import "./globals.css";

// const inter = Inter({ subsets: ["latin"] });

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

// export default function RootLayout({
//   children,
// }: Readonly<{
//   children: React.ReactNode;
// }>) {
//   return (
//     <html lang="en">
//       <body className={inter.className}>{children}</body>
//     </html>
//   );
// }
